# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.


report: "report/workflow.rst"

# Allow users to fix the underlying OS via singularity.
singularity: "docker://continuumio/miniconda3"

include: "rules/common.smk"

rule all:
    input:
        expand("results/star/{sample}Unmapped.out.mate{pair}",sample=samples['sample'], pair=['1','2'])
        # The first rule should define the default target files
        # Subsequent target rules can be specified below. They should start with all_*.



include: "rules/quality_control.smk"
include: "rules/filter_host.smk"
